version: "3.8"

volumes:
  dbdata:

services:
  app:
    build: .
    image: proto/php:dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_PORT=5432
      - DB_HOST=db
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: node:alpine
    working_dir: /home/node
    volumes:
      - ./src:/home/node
    command: ['yarn', 'run', 'watch']

  web:
    image: nginx:alpine
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80